### ISSUE TITLE
Microsoft/opengcs is extremely out of date

### ISSUE THREAD

**Issue by lowenna** [linuxkit/lcow#38]
There have been significant changes over the past 6+ months in the opengcs repo. The Linuxkit repo desperately needs a refresh, especially if it's expected to be used to try-out LCOW and dockerd using containerd as it's runtime for LCOW (see https://github.com/moby/moby/pull/38541). I highly doubt the current version being used/vendored will even boot a container successfully, let alone support what is required.

**Comment by lowenna** [comment]
@justincormack Any idea who could update this repo? (Unless @rn has some free time since moving roles 😆).

**Comment by rn** [comment]
Is is just the opengcs version which needs updating? I can do that but have no means of testing it.

**Comment by lowenna** [comment]
That would be a good start, Rolf. I can verify.

**Comment by rn** [comment]
to be fair the OpenGCS used here is the latest release...
