### ISSUE TITLE
Archive linuxkit/lcow?

### ISSUE THREAD

**Issue by rn** [linuxkit/lcow#54]
Running Linux Containers on Windows has moved towards using WSL. LCOW support is still experimental in docker itself and it's hard to track. For this reason this project has been more or less dormant and I propose to archive it.

@justincormack @deitch @dave-tucker please chime in.

**Comment by dave-tucker** [comment]
Yes this makes sense. I agree that it should be archived.

**Comment by justincormack** [comment]
Currently Docker Desktop is still shipping this code, although in experimental mode. Am discussing with them timetable for removing.

**Comment by aplocher** [comment]
Might I suggest at least updating the README.md to no longer say it's under active development? :)

> Note: LCOW support is currently experimental and under active development.

**Comment by rn** [comment]
@justincormack have you had a chance to find out about the time line. If this is used in Docker Desktop I suggest someone from that team to support it.

**Comment by justincormack** [comment]
This will now be archived, I will update the README
