### ISSUE TITLE
Bind mount host to container: very slow write speed

### ISSUE THREAD

**Issue by Yivan** [linuxkit/lcow#7]
Hello,

I just tried Docker for Windows with the LCOW feature activated (edge version + experimental).
I made:
```
docker run -it --rm --platform linux -v C:\:/c debian:stretch-slim bash
cd /c
dd if=/dev/zero of=./output bs=8k count=10k; rm -f ./output
```

It give a writing speed of around 40 MB/s.

Comparing to other possibilities, where:
- Docker for Windows (Samba share, the native share) give 120 MB/s
- Docker for Windows (NFS volume by using a NFS server on windows host) give 230 MB/s

And outside the container world:
- Windows subsytem linux (Ubuntu, DrvFs in /mount/c) give 830 MB/s
- Git Bash on Windows give 1.2 GB/s (native speed of the hard drive so)

I was hoping LCOW will bring some same technologie as the DrvFs used in Windows subsystem linux... but it doesn't seem.

Is it normal it is so slow ? Is there way i can improve it ? I know it is experimental for now and in current development, but will there be improvement on shared data between host and containers ?

Thanks.

**Comment by rn** [comment]
Thanks for reporting this issue, but this is not really related to the LinuxKit implementation so I'm closing this here. I would suggest to open an issue on where the Microsoft developers are more likely getting pinged. Thanks
